package com.afrobad.VeinLinker.registrationandlogin.cache.drafts;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.afrobad.VeinLinker.registrationandlogin.cache.enums.*;
import com.afrobad.VeinLinker.registrationandlogin.uploadedfile.enums.VerificationDocumentType;
import com.afrobad.VeinLinker.registrationandlogin.users.enums.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;

/**
 * Temporary registration state stored in Redis.
 *
 * This object exists only until registration is completed.
 * After final submission, it is converted into:
 * - Users entity
 * - Files entity
 * - UserFile entity
 *
 * Then removed from Redis.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RegistrationDraft {

    // ==========================================================
    // DRAFT METADATA or System Fields (Generated by System)
    // ==========================================================
    // Note: No validations here because the system populates these.

    private String draftId;

    private Integer currentStep;

    private RegistrationStatus registrationStatus;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    // ==========================================================
    // FORM 1
    // ==========================================================

    @NotNull(message = "Role is required")
    private Role role;

    @NotBlank(message = "Full name cannot be empty")
    @Size(min = 2, max = 100, message = "Full name must be between 2 and 100 characters")
    private String fullName;

    @NotBlank(message = "Email address cannot be empty")
    @Email(message = "Please provide a valid email address")
    private String email;

    @NotBlank(message = "Phone number cannot be empty")
    @Pattern(regexp = "^\\+?[0-9]{10,15}$", message = "Please provide a valid phone number (10 to 15 digits)")
    private String phone;

    /**
     * Store BCrypt hash only.
     * Never store raw password.
     */
    @NotBlank(message = "Password hash is missing")
    private String passwordHashFormat;

    // ==========================================================
    // FORM 2
    // ==========================================================

    @NotBlank(message = "Father's name cannot be empty")
    private String fathersName;

    @NotBlank(message = "Mother's name cannot be empty")
    private String mothersName;

    @NotNull(message = "Date of birth is required")
    @Past(message = "Date of birth must be a date in the past")
    private LocalDate dob;

    @NotNull(message = "Gender selection is required")
    private Gender gender;

    @NotNull(message = "Height is required")
    @DecimalMin(value = "30.0", message = "Height must be a realistic value in cm")
    @DecimalMax(value = "300.0", message = "Height must be a realistic value in cm")
    private BigDecimal height;

    @NotNull(message = "Weight is required")
    @DecimalMin(value = "2.0", message = "Weight must be a realistic value in kg")
    @DecimalMax(value = "500.0", message = "Weight must be a realistic value in kg")
    private BigDecimal weight;

    @NotNull(message = "Religion is required")
    private Religion religion;

    @NotNull(message = "Marital status is required")
    private MaritalStatus maritalStatus;

    @NotNull(message = "Blood group is required")
    private BloodGroup bloodGroup;

    @NotNull(message = "Rh factor is required")
    private RhFactor rhFactor;
    

    // ==========================================================
    // FORM 3
    // ==========================================================
    
    @NotNull(message="Document type is required")
    private VerificationDocumentType verificationDocumentType;

    /**
     * Uploaded documents associated with this draft.
     */
    @NotEmpty(message = "At least one registration document must be uploaded")
    @Builder.Default
    private List<@Valid UploadedFileDraft> uploadedDocuments = new ArrayList<>();
}