CREATE TABLE users (
    internal_userID BIGINT PRIMARY KEY AUTO_INCREMENT,
    encrypted_userID CHAR(36) NOT NULL UNIQUE,
    public_userID VARCHAR(15) NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    fathers_name VARCHAR(255) NOT NULL,
    mothers_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    height DECIMAL(5, 2) NOT NULL,
    weight DECIMAL(5, 2) NOT NULL,
    marital_status ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED') NOT NULL,
    blood_group ENUM('A', 'B', 'AB', 'O'),
    rh_factor ENUM('POSITIVE', 'NEGATIVE'),
    nid_image_url VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255) NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    nid_verified BOOLEAN NOT NULL DEFAULT FALSE,
    account_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    last_active_mode VARCHAR(50),
    donation_count INT NOT NULL DEFAULT 0,
    receiving_count INT NOT NULL DEFAULT 0,
    points INT NOT NULL DEFAULT 0,
    level INT NOT NULL DEFAULT 0,
    reliability_score INT NOT NULL DEFAULT 100,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);